### ISSUE TITLE
Would like a way to add dependencies outside of the capsule root

### ISSUE THREAD

**Issue by yrro** [puniverse/capsule#67]
As discussed at <https://groups.google.com/forum/#!topic/capsule-user/1kkx8-Y58R0>, it would be nice to have a way for caplets to add dependencies outside of the capsule root.

For instance, client libraries in the Hadoop ecosystem require their configuration to be loaded from the classpath. Currently my attempt to write a capsule for this results in:

```
CAPSULE EXCEPTION: Could not resolve item /etc/hive/conf while processing attribute Dependencies: [/etc/hive/conf]
java.lang.RuntimeException: Could not resolve item /etc/hive/conf
	at Capsule.resolve(Capsule.java:2781)
	at Capsule.resolve(Capsule.java:2813)
	at Capsule.buildClassPath(Capsule.java:1864)
	at Capsule.buildJavaProcess(Capsule.java:1744)
	at Capsule.buildProcess0(Capsule.java:1273)
	at Capsule.buildProcess(Capsule.java:1264)
	at Capsule.buildProcess(Capsule.java:1264)
	at Capsule.buildProcess(Capsule.java:1264)
	at Capsule.prelaunch0(Capsule.java:1237)
	at Capsule.prelaunch(Capsule.java:1232)
	at Capsule.prelaunch(Capsule.java:1232)
	at Capsule.prelaunch(Capsule.java:1232)
	at Capsule.prepareForLaunch(Capsule.java:1146)
	at Capsule.launch(Capsule.java:1091)
	at Capsule.main0(Capsule.java:332)
	at Capsule.main(Capsule.java:311)
Caused by: java.lang.IllegalArgumentException: Path /etc/hive/conf is not local to app cache /home/sam/.capsule/apps/hivelint.HiveLint_0.1.2147483647
	at Capsule.sanitize(Capsule.java:3003)
	at Capsule.resolve(Capsule.java:2768)
	... 15 more
```

**Comment by pron** [comment]
To add dependencies outside the capsule, you need a caplet (this, too, was prohibited, but now allowed; See #65). Otherwise, there is no portable way of locating the directory from the manifest.

**Comment by yrro** [comment]
Yes, I've written such a caplet--but capsule itself doesn't allow the modified `ATTR_DEPENDENCIES` to contain paths outside of the capsule root. Or am I overriding the wrong thing?

**Comment by pron** [comment]
This has been resolved (#65) in rc2-SNAPSHOT.

**Comment by pron** [comment]
Also, while you're welcome to use the SNAPSHOT version, if you're not in a hurry I suggest you wait a few weeks for the 1.0 final release (there will probably be no rc2 release) as the internal API is in a bit of a flux. I'm just making sure that various caplets can actually be expressed with the API before releasing the final version.

**Comment by yrro** [comment]
Ah, thanks for the pointer. I've looked at the current 1.0-rc2-SNAPSHOT though and as far as I can tell sanitize still throws if the path is absolute and is outside the capsule root or the JRE directory. I'm looking at https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L3497.

**Comment by pron** [comment]
Yes, but `sanitize` is now only called on values taken from the manifest -- not those returned from caplets (that's how it should work, at least). The values in the manifest still shouldn't point outside the capsule (except to $JAVA_HOME, which is guaranteed to exist, `cause we know Java is running).

**Comment by yrro** [comment]
Indeed, sorry for the confusion. I've got it working now--thanks for the help!
